version: '3.8'

services:
  backend:
    build: .
    container_name: yt_notes_backend
    env_file:
      - .env
    ports:
      - "5001:5000"
    restart: unless-stopped
    volumes:
      - ./server/database/notes.db:/app/database/notes.db